### PR TITLE
Pull request to merge the new features on the master branch

### PR DESCRIPTION
**Pull request by FrancoRosa**
- We added the images in the nav-bar.
- Fixed the nav-bar and footer width.
- Fixed the video section.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your did a good job so far :+1:

#### In future projects I am asking you not to close pull request after first review. You can make commits and submit new review requests using same pull request.

* [x] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.

* [x] Logo image is not displaying right now, that should be fixed:
image

* [x] Navigation bar is not aligned properly, please make look more like original:

image

Original:

image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by FrancoRosa** [comment]
Hello! @pelzolga123 

Thank you for your kind review!

- [ ] We already fixed the errors shown on the validator

- [ ] We align the elements on the nav bar

- [ ] We are using a URL for the logo and it shows properly on the left corner of the page.

Please take a look at it again

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🛑 👀 🔍 
****
### Hi Team. 😄 
### Very good job so far, I notice you do a great job implementing the changes required by the previous TSE 🎊 
**Before move on let's solve a couple of issues.**  💯 👨‍💻  

****
- [ ] Video.

The video doesn't fit with the iframe div.
Here is how it looks: 

Screen Shot 2020-02-20 at 6 41 10 PM

Kindly fix that following this youtube page as a guide: [example](https://www.youtube.com/watch?v=V74l_zS1x8E)

I'll recommend you to remove the width and height from the HTML 'frame div', you can add this property using CSS (height and width).

Screen Shot 2020-02-20 at 6 54 34 PM
****

****
**Implementation details**

- [ ]  Comment section.

Kindly add the comments section, you can follow this example:

Screen Shot 2020-02-20 at 6 42 39 PM
****

****

- [ ] Stickler.

Screen Shot 2020-02-20 at 6 43 59 PM

This looks like there's no stickler configuration file.

****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
